trigger:
  branches:
    include:
    - main
    - release/*
variables:
- name: buildConfiguration
  value: 'Release'
- name: packageVersion
  value: '1.0.0-preview6'
- name: efPackageVersion
  value: '1.0.0-preview5'
- name: identityPackageVersion
  value: '1.0.0-preview6'
- name: RunSqlServerTest
  value: 'true'
stages:
- stage: __default
  jobs:
  - job: ''
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
          shouldPack: false
        mac:
          imageName: 'macOS-latest'
          shouldPack: false
        windows:
          imageName: 'windows-latest'
          shouldPack: true
    pool:
      vmImage: $(imageName)
    steps:
    - task: Bash@3
      displayName: Create LocalNuget folder
      inputs:
        targetType: inline
        script: |
          mkdir LocalNuget
        workingDirectory: $(Build.SourcesDirectory)
#    - task: PowerShell@2
#      condition: and(succeeded(), eq(variables['shouldPack'], true))
#      displayName: 'Update build date'
#      inputs:
#        filePath: 'setBuildDate.ps1'
    - task: UseDotNet@2
      displayName: Install .NET Core sdk version 5.x
      inputs:
        packageType: sdk
        version: 5.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: UseDotNet@2
      displayName: Install .NET Core sdk version 3.1.x
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: UseDotNet@2
      displayName: Install .NET Core sdk version 6.0.x
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: 5.4.0
    - task: CmdLine@2
      displayName: 'Set build version'
      env:
        Action: '##vso[build.updatebuildnumber]'
        BuildVersion: $(packageVersion)
      inputs:
        script: echo %Action%%BuildVersion%
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore'
      inputs:
        command: 'restore'
        projects: >+
          **/Rsk.Audit.csproj
  
          **/Rsk.Audit.Tests.Common.csproj
  
          **/Rsk.Audit.Tests.Integration.csproj
  
          feedsToUse: 'config'
          nugetConfigPath: $(System.DefaultWorkingDirectory)/NuGet.AzDO.config        
 