trigger: none
pr: none

variables:
- group: "NugetPackageRelease"
- name: buildConfiguration
  value: 'Release'
- name: efPackageVersion
  value: '4.0.0.0'

stages:
- stage: Build
  jobs:
  - job: BuildRskAuditEF
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
          shouldPack: true
        mac:
         imageName: 'macOS-latest'
         shouldPack: true
        windows:
          imageName: 'windows-latest'
          shouldPack: true
    pool:
      vmImage: $(imageName)
    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core sdk version 10.x
      inputs:
        packageType: sdk
        version: 10.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: 5.4.0
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore'
      inputs:
        command: 'restore'
        projects: 'src/Rsk.Audit.EF/Rsk.Audit.EF.csproj'
        feedsToUse: 'config'
        nugetConfigPath: $(System.DefaultWorkingDirectory)/NuGet.AzDO.config
    - task: DotNetCoreCLI@2
      displayName: dotnet build src/Rsk.Audit.EF/Rsk.Audit.EF.csproj
      inputs: 
        command: 'build'
        projects: 'src/Rsk.Audit.EF/Rsk.Audit.EF.csproj'
        arguments: -c $(buildConfiguration) --no-restore /p:Version="$(efPackageVersion)"
    - task: DotNetCoreCLI@2
      displayName: dotnet test - Run Rsk.Audit.EF Tests
      inputs: 
        command: 'test'
        projects: 'tests/Rsk.Audit.Tests.Integration/Rsk.Audit.Tests.Integration.csproj'
        arguments: -c $(buildConfiguration) --no-restore
    - task: DotNetCoreCLI@2
      displayName: Package Rsk.Audit.EF.csproj for Nuget
      inputs:
        command: 'pack'
        packagesToPack: 'src/Rsk.Audit.EF/Rsk.Audit.EF.csproj'
        nobuild: true
        includesymbols: true
        versionEnvVar: efPackageVersion
        versioningScheme: 'byEnvVar'
        verbosityPack: 'Normal'
        outputDir: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), eq(variables['shouldPack'], true))
      displayName: Publish Rsk.Audit.EF artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Rsk.Audit.EF nupkg'
        publishLocation: 'Container'

- stage: Publish
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: PublishNuGet
    environment: Release
    strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/publish-nuget.yml
                parameters:
                  toLive: true
                  artifact: 'Rsk.Audit.EF nupkg'
                  packageToPublish: '$(Pipeline.Workspace)/Rsk.Audit.EF nupkg/*.nupkg'